### ISSUE TITLE
Support fluidStart that matches value in the breakpoints array

### ISSUE THREAD

**Issue by elitenoire** [galacemiguel/fluid-system#6]
Supposing I have `breakpoints array = ['20em', '30em', '40em']`

And `fontSizes array = ['0.75em', '0.875em','1em','1.125em','1.375em']`

And I set `fluidStart = 20em` which is the first breakpoint in my array

And I want to use `fluid fontsizes = [2, 3, 4] // 1em, 1.125em, 1.37em @ 20em, 30em, 40em bps`

Setting `fluidStart` to the same value as a breakpoint in the array doesn't produce the correct fluid font sizes.
The `1.125em fontsize` is being used to calculate fluid font between `20em and 30em bps`  instead of the `1em fontsize` .

It works as in your example if the `fluidStart` value isn't in the breakpoints array so that bp array becomes only `['30em','40em']`. But I don't want to change my bp array as it is being used for other components design.

**Comment by galacemiguel** [comment]
Thanks for raising this issue, @elitenoire! I'll put out a fix in the next release. Thanks!

**Comment by galacemiguel** [comment]
Hey, @elitenoire! Sorry for the late reply. I've had some time to come back to this now and, after having tried your example, I do believe that Fluid System is working as expected.

```javascript
const theme = {
  breakpoints: ["20em", "30em", "40em"],
  fontSizes: ["0.75em", "0.875em", "1em", "1.125em", "1.375em"]
};

theme.breakpoints.fluidStart = "20em";
```

Without using Fluid System, assigning `fontSize={[2, 3, 4]}` given your conditions produces the following styles:
```css
body {
  font-size: 1em;
}

@media screen and (min-width: 20em) {
  body {
    font-size: 1.125em;
  }
}

@media screen and (min-width: 30em) {
  body {
    font-size: 1.375em;
  }
}
```

Graphed, that looks like this:
![example-1](https://user-images.githubusercontent.com/7394331/72678707-6d106680-3ae3-11ea-92ff-052953fc08bd.png)

Therefore, Fluid System should draw straight lines between the remaining breakpoints, starting from the declared `fluidStart (20em)`:
```css
body {
  font-size: 1em;
}

@media screen and (min-width: 20em) {
  body {
    font-size: calc(1.125em + (1.375 - 1.125)*(100vw - 20em)/(30 - 20));
  }
}

@media screen and (min-width: 30em) {
  body {
    font-size: 1.375em;
  }
}
```

![example-2](https://user-images.githubusercontent.com/7394331/72678828-91207780-3ae4-11ea-8ead-5be919d800fe.png)

Is this different from what you expected?
